name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: |
        npm ci

    - name: Install dependencies
      run: npm install
    
    - name:  Run tests 
      run: npm test
      
    - name: Run tests and coverage
      run: npm test -- --coverage
  
    - name: Upload coverage to Coveralls
      env:
          CI: true
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
          npm install -g coveralls
          coveralls

    # - name: Run Tests
    #   run: |
    #     npm test
    # - name: npm install, make test-coverage
    #   run: |
    #     npm install
    #     make test-coverage

    # - run: npm run test-coverage
  
    # - name: Coveralls
    #   uses: coverallsapp/github-action@v2
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    
    # - name: Publish to coveralls.io
    #   uses: coverallsapp/github-action@v2
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
